// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1789600284);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1789600284);
user_pref("app.update.lastUpdateTime.glean-addons-daily", 1789600284);
user_pref("app.update.lastUpdateTime.region-update-timer", 1789600284);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1789600284);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1789600284);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 172);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b9076cf5-beec-4de4-8b35-b94a8b2eeda7}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "never");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\",\"webcompat@mozilla.org\",\"screenshots@mozilla.org\",\"pictureinpicture@mozilla.org\",\"formautofill@mozilla.org\"]");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20260831224056");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.lastColdStartupCheck", 1789600390);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"reset-pbm-toolbar-button\",\"unified-extensions-button\",\"new-tab-button\",\"alltabs-button\",\"personal-bookmarks\",\"ublock0_raymondhill_net-browser-action\"],\"TabsToolbar\":[\"tabbrowser-tabs\"],\"vertical-tabs\":[],\"PersonalToolbar\":[]},\"seen\":[\"reset-pbm-toolbar-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"TabsToolbar\",\"vertical-tabs\",\"PersonalToolbar\"],\"currentVersion\":24,\"newElementCount\":2}");
user_pref("captchadetection.lastSubmission", 1789600);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "b0bacafe-b0ba-cafe-b0ba-cafeb0bacafe");
user_pref("datareporting.dau.cachedUsageProfileID", "beefbeef-beef-beef-beef-beeefbeefbee");
user_pref("datareporting.policy.firstRunURL", "https://www.mozilla.org/privacy/firefox/");
user_pref("distribution.iniFile.exists.appversion", "152.0.4-beta.30");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.filesystem.pathcheck.disabled", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.lastAppBuildId", "20260831224056");
user_pref("extensions.lastAppVersion", "152.0.4-beta.30");
user_pref("extensions.lastPlatformVersion", "152.0.4");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"ae036142-8c0e-4934-8ded-21bf5da14d7c\",\"formautofill@mozilla.org\":\"335e9b3f-9541-4360-a515-692a9a37bbf2\",\"ipp-activator@mozilla.com\":\"e0a399cf-66aa-4cbe-8b70-d752094350ae\",\"pictureinpicture@mozilla.org\":\"3f88557f-ca5c-4d22-ba8c-e5b66395ca6d\",\"addons-search-detection@mozilla.com\":\"496b7089-e7b1-4d29-9b6f-55e2b6fa67d6\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"601fd53e-fb4b-45f4-9531-8de2b3057fbe\",\"firefox-compact-dark@mozilla.org\":\"27f56924-7dc7-49e5-9011-6ac259d16679\",\"uBlock0@raymondhill.net\":\"f2ac1d74-cc85-4c0b-b558-7f2d37b455a7\"}");
user_pref("font.system.whitelist", "Arial,Calibri,Cambria Math,Consolas,Courier New,Georgia,Nirmala UI,Segoe UI,Tahoma,Times New Roman,Trebuchet MS,Verdana,MS PGothic,Microsoft YaHei UI,Yu Gothic UI Light,SimSun,Wingdings,Malgun Gothic,Segoe UI Light,Impact,Microsoft JhengHei Light,Segoe UI Historic,Malgun Gothic Semilight,Yu Gothic UI Semilight,MingLiU_HKSCS-ExtB,游ゴシック,細明體-ExtB,맑은 고딕,Yu Gothic UI Semibold,Yu Gothic Medium,Segoe UI Black,Myanmar Text,PMingLiU-ExtB,新宋体,Microsoft JhengHei UI Light,Microsoft JhengHei UI,微軟正黑體,Twemoji Mozilla,Ink Free,Nirmala UI Semilight,Arial Black,Gabriola,맑은 고딕 Semilight,Cambria,Microsoft YaHei Light,ＭＳ Ｐゴシック,Marlett,Franklin Gothic Medium,Segoe UI Variable,Candara Light,Microsoft YaHei,MS UI Gothic,Yu Gothic,Segoe Script");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.getdisplaymedia.screencapturekit.enabled", false);
user_pref("media.getdisplaymedia.screencapturekit.picker.enabled", false);
user_pref("media.gmp-manager.buildID", "20260831224056");
user_pref("media.gmp-manager.lastCheck", 1789600277);
user_pref("media.gmp-manager.lastEmptyCheck", 1789600277);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.profileId", "5e1151c4-061c-4ffe-9f62-d5a9aaf3e30d");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("security.sandbox.warn_unprivileged_namespaces", false);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"bookmarksExpandedFolders\":[],\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.profiles.storeID", "73bf0536");
user_pref("toolkit.startup.last_success", 1789600387);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.cachedProfileGroupID", "decafdec-afde-cafd-ecaf-decafdecafde");
user_pref("toolkit.telemetry.previousBuildID", "20260831224056");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("webgl.force-enabled", true);
